### PR TITLE
Update to Polymer 1.8, use Shadow DOM v1 syntax

### PR DESCRIPTION
**Pull request by tomalec**
To be forward compatible with Web Components V1 and Polymer 2.0

### CODE REVIEW

**Comment by warpech** [comment]
This implements https://github.com/display-interactive/pikaday-decorator/issues/2

**Comment by Diwatt** [comment]
Thank you guys for what you've done.

**Comment by warpech** [comment]
Thank you for a nice custom element :) Would you please release a version?

**Comment by Diwatt** [comment]
of course sorry !

**Pull request merged**
